<a href="https://colab.research.google.com/github/sksaket/Assignment-on-neural-network/blob/main/Gas_turbines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd
import numpy as np
#Plot Tools
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
#Model Building
from sklearn.preprocessing import StandardScaler
import sklearn
import keras
from keras.wrappers.scikit_learn import KerasRegressor
from keras.models import Sequential
from keras.layers import InputLayer,Dense
import tensorflow as tf
#Model Validation
from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.metrics import mean_squared_error

In [40]:
data=pd.read_csv('/content/gas_turbines.csv')
data

AT      AP      AH    AFDP  ...     TEY     CDP      CO     NOX
0      6.8594  1007.9  96.799  3.5000  ...  114.70  10.605  3.1547  82.722
1      6.7850  1008.4  97.118  3.4998  ...  114.72  10.598  3.2363  82.776
2      6.8977  1008.8  95.939  3.4824  ...  114.71  10.601  3.2012  82.468
3      7.0569  1009.2  95.249  3.4805  ...  114.72  10.606  3.1923  82.670
4      7.3978  1009.7  95.150  3.4976  ...  114.72  10.612  3.2484  82.311
...       ...     ...     ...     ...  ...     ...     ...     ...     ...
15034  9.0301  1005.6  98.460  3.5421  ...  111.61  10.400  4.5186  79.559
15035  7.8879  1005.9  99.093  3.5059  ...  111.78  10.433  4.8470  79.917
15036  7.2647  1006.3  99.496  3.4770  ...  110.19  10.483  7.9632  90.912
15037  7.0060  1006.8  99.008  3.4486  ...  110.74  10.533  6.2494  93.227
15038  6.9279  1007.2  97.533  3.4275  ...  111.58  10.583  4.9816  92.498

[15039 rows x 11 columns]

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15039 entries, 0 to 15038
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      15039 non-null  float64
 1   AP      15039 non-null  float64
 2   AH      15039 non-null  float64
 3   AFDP    15039 non-null  float64
 4   GTEP    15039 non-null  float64
 5   TIT     15039 non-null  float64
 6   TAT     15039 non-null  float64
 7   TEY     15039 non-null  float64
 8   CDP     15039 non-null  float64
 9   CO      15039 non-null  float64
 10  NOX     15039 non-null  float64
dtypes: float64(11)
memory usage: 1.3 MB


In [42]:
data.describe()

AT           AP  ...            CO           NOX
count  15039.000000  15039.00000  ...  15039.000000  15039.000000
mean      17.764381   1013.19924  ...      1.972499     68.190934
std        7.574323      6.41076  ...      2.222206     10.470586
min        0.522300    985.85000  ...      0.000388     27.765000
25%       11.408000   1008.90000  ...      0.858055     61.303500
50%       18.186000   1012.80000  ...      1.390200     66.601000
75%       23.862500   1016.90000  ...      2.160400     73.935500
max       34.929000   1034.20000  ...     44.103000    119.890000

[8 rows x 11 columns]

In [43]:
X = data.loc[:,['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'CDP', 'CO','NOX']]
y= data.loc[:,['TEY']]

In [44]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
y = scaler.fit_transform(y)

In [45]:
def baseline_model():
    model = Sequential()
    model.add(Dense(10, input_dim=10, activation='tanh'))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [46]:
estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=50, batch_size=100, verbose=False)
kfold = KFold(n_splits=10)
results = cross_val_score(estimator, X, y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  """Entry point for launching an IPython kernel.


Results: -0.16 (0.16) MSE


In [47]:
estimator.fit(X, y)
prediction = estimator.predict(X)

In [48]:
prediction

array([-1.1115861, -1.1300446, -1.1444327, ..., -1.5840818, -1.2675691,
       -1.1411753], dtype=float32)

In [49]:
prediction.shape


(15039,)

In [50]:
prediction = prediction.reshape(-1, 1) 

In [51]:
a=scaler.inverse_transform(prediction)
a

array([[116.59296],
       [116.30077],
       [116.07302],
       ...,
       [109.11373],
       [114.12387],
       [116.12458]], dtype=float32)

In [52]:
b=scaler.inverse_transform(y)
b

array([[114.7 ],
       [114.72],
       [114.71],
       ...,
       [110.19],
       [110.74],
       [111.58]])

In [53]:
mean_squared_error(b,a)

17.833294984991237

In [54]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [55]:
estimator.fit(X_train, y_train)
prediction = estimator.predict(X_test)

In [56]:
prediction

array([-0.12870032, -0.73417044,  0.18146873, ..., -1.4127524 ,
       -1.0911119 ,  1.9734464 ], dtype=float32)

In [57]:
 prediction = prediction.reshape(-1, 1) 

In [58]:
c=scaler.inverse_transform(prediction)

In [59]:
d=scaler.inverse_transform(y_test)

In [60]:
mean_squared_error(d,c)

71.23869257561199